FROM golang:1.24-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/order-generator/ ./cmd/order-generator/
COPY config/ ./config/
COPY internal/ ./internal/

RUN go build -o order-generator ./cmd/order-generator

CMD ["./order-generator"]